.mode column
PRAGMA foreign_keys = ON; -- activates foreign key features in sqlite. It is disabled by default

CREATE TABLE HOUSES (
    HOUSEID INTEGER PRIMARY KEY,
    SELLERNAME VARCHAR(20),
    NUMBEROFBEDROOMS INTEGER,
    NUMBEROFBATHROOMS INTEGER,
    PRICE INTEGER,
    ZIPCODE INTEGER,
    LISTINGDATE DATETIME,
    AGENTNAME VARCHAR(20),
    OFFICE VARCHAR(20),
    STATUS INTEGER
);

CREATE TABLE SALES (
    SALEID INTEGER PRIMARY KEY,
    HOUSEID INTEGER,
    BUYERRNAME VARCHAR(20),
    SALEPRICE INTEGER,
    AGENTNAME VARCHAR(20),
    SOLDDATE DATETIME, 
    OFFICE VARCHAR(20),
    FOREIGN KEY (HOUSEID) REFERENCES HOUSES(HOUSEID),
    FOREIGN KEY (AGENTNAME) REFERENCES HOUSES(AGENTNAME)
);

INSERT INTO HOUSES VALUES (1, 'Neha Haines', 2, 1, 250000, 14738, '2022-11-01 8:00:00', 'Pamela Charles', 'New York', "Not Sold");
INSERT INTO HOUSES VALUES (2, 'Luis Taylor', 3, 1, 450000, 84003, '2022-11-02 8:00:00', 'Timothy Hansen', 'New York', "Not Sold");
INSERT INTO HOUSES VALUES (3, 'Neha Haines', 4, 2, 500000, 34003, '2022-11-03 8:00:00', 'Pamela Charles', 'New York', "Not Sold");


INSERT INTO SALES VALUES (10, 1, 'Lacie Rollins', 250000, 'Pamela Charles', '2022-11-05 8:00:00', 'New York');
INSERT INTO SALES VALUES (11, 3, 'Alice Christian', 450000, 'Pamela Charles', '2022-11-05 8:00:00', 'New York');
INSERT INTO SALES VALUES (12, 2, 'Alice Christian', 450000, 'Timothy Hansen', '2022-11-05 8:00:00', 'San Francisco');


SELECT '';
SELECT "Find the top 5 offices with the most sales for that month";
SELECT '----------------------------------------------------';
SELECT OFFICE FROM SALES
    GROUP BY OFFICE
    ORDER By COUNT(*) DESC LIMIT 5;

    
SELECT '';
SELECT "Find the top 5 estate agents who have sold the most for the month (include their contact details and their sales details so that it is easy contact them and congratulate them)";
SELECT '----------------------------------------------------';
SELECT AGENTNAME FROM SALES
    GROUP BY AGENTNAME
    ORDER By COUNT(*) DESC LIMIT 5;

SELECT '';
SELECT "Calculate the commission that each estate agent must receive and store the results in a separate table";
SELECT '----------------------------------------------------';

CREATE TABLE AGENTCOMISSIONS AS 
SELECT AGENTNAME, @COMMISSION = SALEPRICE * 0.1 FROM SALES WHERE SALEPRICE < 100000 union all
SELECT AGENTNAME, @COMMISSION = SALEPRICE * 0.075 FROM SALES WHERE SALEPRICE > 100000 and SALEPRICE < 200000 union all
SELECT AGENTNAME, @COMMISSION = SALEPRICE * 0.06 FROM SALES WHERE SALEPRICE > 200000 and SALEPRICE < 500000 union all
SELECT AGENTNAME, @COMMISSION = SALEPRICE * 0.05 FROM SALES WHERE SALEPRICE > 500000 and SALEPRICE < 1000000 union all
SELECT AGENTNAME, @COMMISSION = SALEPRICE * 0.04 FROM SALES WHERE SALEPRICE > 1000000;

CREATE TABLE AGENTCOMISSIONS AS 
SELECT AGENTNAME, SALEPRICE * 0.1 FROM SALES WHERE SALEPRICE < 100000 union all
SELECT AGENTNAME, SALEPRICE * 0.075 FROM SALES WHERE SALEPRICE > 100000 and SALEPRICE < 200000 union all
SELECT AGENTNAME, SALEPRICE * 0.06 FROM SALES WHERE SALEPRICE > 200000 and SALEPRICE < 500000 union all
SELECT AGENTNAME, SALEPRICE * 0.05 FROM SALES WHERE SALEPRICE > 500000 and SALEPRICE < 1000000 union all
SELECT AGENTNAME, SALEPRICE * 0.04 FROM SALES WHERE SALEPRICE > 1000000;

SELECT * FROM AGENTCOMISSIONS;

SELECT AGENTNAME, SUM(SALEPRICE) FROM AGENTCOMISSIONS GROUP BY AGENTNAME;

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'HOUSES'
ORDER BY ORDINAL_POSITION

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'HOUSES'


DROP TABLE AGENTCOMISSIONS;


SELECT '';
SELECT "For all houses that were sold that month, calculate the average number of days on the market";
SELECT '----------------------------------------------------';
SELECT NAME FROM RUBY
    JOIN RACES ON RACES.RACEID = RUBY.RACEID
    WHERE RUBY.RACEID = 1
    ORDER By RUBY.RUNTIME;


SELECT '';
SELECT "For all houses that were sold that month, calculate the average selling price";
SELECT '----------------------------------------------------';
SELECT NAME FROM RUBY
    JOIN RACES ON RACES.RACEID = RUBY.RACEID
    WHERE RUBY.RACEID = 1
    ORDER By RUBY.RUNTIME;
    
    
